### PR TITLE
Added support for Struts v6.x

### PR DESCRIPTION
**Pull request by burtonrhodes**
- This PR adds DTD references for Struts versions 6.x
- Additionally, there seems to have been a mistake when copying over the original code to the "intellij-obsolete-plugins" repository.  All the com.intellij.lang.ognl.** classes were in the wrong directory structure.

### CODE REVIEW

**Comment by burtonrhodes** [comment]
In case anyone needs to use this release prior to PR acceptance, you can download the plugin package here: [https://github.com/burtonrhodes/intellij-obsolete-plugins/releases/tag/v2023.2.2](https://github.com/burtonrhodes/intellij-obsolete-plugins/releases/tag/v2023.2.2)

**Review by YannCebron — CHANGES_REQUESTED** [review]
The commit a69e8747646d256a893410f68268e34e3c50e4d1 seems wrong, package names should never change here. Same with 6b0985e180ce554323a7b707e045f4caf27984ff.
The PR misses adding testdata to verify that Struts 6.x DTD is correctly handled now.

**Comment by burtonrhodes** [comment]
Thanks for the feedback. I will take a look next week when I get back from vacation.

**Comment by burtonrhodes** [comment]
@YannCebron I am attempting to undo the package refactor and implement the tests, but I have 2 questions: 

1) I am confused as to why the package structure should not be "fixed". For all `com.intellij.struts2.ognl.*` classes, the folder structure does not match the package name `com.intellij.lang.ognl.*`. ([example](https://github.com/JetBrains/intellij-obsolete-plugins/blob/master/struts2/src/main/java/com/intellij/struts2/ognl/OgnlFile.java)) Additionally, there is a [/test/intellij/lang/ognl](https://github.com/JetBrains/intellij-obsolete-plugins/tree/master/struts2/src/test/java/com/intellij/lang/ognl) folder where both the package name and folder structure match. (`test/java/com/intellij/lang/ognl/**` not `test/java/com/intellij/struts2/ognl/**`). I feel like this is inconsistent - not to mention all the errors I get from within the IDE itself. (I'm also confused as to how the project successfully compiles with mismatched package names/folders). In any event, I will revert the commit, but just thought I would ask the question.

2) I am unable to get any test to run with the error below from intellij.  I've googled this error trying to find a solution without success.  Another user [posted this](https://intellij-support.jetbrains.com/hc/en-us/community/posts/8438635703570-java-lang-IllegalAccessError-class-com-intellij-testFramework-UITestUtil-cannot-access-class-sun-awt-AWTAutoShutdown) to intellij support, but it seems no answer was provided. Any thoughts on how I might fix this?

```
java.lang.IllegalAccessError: class com.intellij.testFramework.UITestUtil (in unnamed module @0x7f560810) cannot access class sun.awt.AWTAutoShutdown (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x7f560810

	at com.intellij.testFramework.UITestUtil.replaceIdeEventQueueSafely(UITestUtil.java:73)
	at com.intellij.testFramework.UsefulTestCase.runBare(UsefulTestCase.java:484)
	at com.intellij.testFramework.UsefulTestCase.runBare(UsefulTestCase.java:477)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

**Comment by burtonrhodes** [comment]
Closing this PR. Going to clean up branch commits in my fork and then resubmit.

**Pull request closed without merging**
